name: 'Validate Solution'
description: 'Validate and preview CARML Bicep solution'

inputs:
  subscriptionId:
    description: 'The subscriptionId to deploy to'
    required: true
  location:
    description: 'The location to use for deployment'
    required: false
  templateFilePath:
    description: 'The path to the template file to use for deployment'
    required: true
  parameterFilePath:
    description: 'The path to the parameter file to use for deployment'
    required: true


runs:
  using: 'composite'
  steps:

    # --------------------------------------#
    #  Validate the Subscription Deployment #
    # --------------------------------------#
    - name: 'Validate [${{ inputs.subscriptionId }}] Azure subscription deployment'
      shell: pwsh
      run: |
        Select-AzSubscription ${{ inputs.subscriptionId }}

        Test-AzDeployment `
          -Location ${{ inputs.location }} `
          -TemplateFile ${{ inputs.templateFilePath }} `
          -TemplateParameterFile ${{ inputs.parameterFilePath }} `
          -Verbose

    # -------------------------#
    #  Subscription Deployment #
    # -------------------------#
    - name: 'Validate [${{ inputs.subscriptionId }}] Azure subscription deployment'
      shell: pwsh
      run: |
        Select-AzSubscription ${{ inputs.subscriptionId }}

        New-AzSubscriptionDeployment `
          -Location ${{ inputs.location }} `
          -TemplateFile ${{ inputs.templateFilePath }} `
          -TemplateParameterFile ${{ inputs.parameterFilePath }} `
          -Verbose
