name: Basic Web App Pipeline
on:
  push:
    branches:
    - main

env:
  #solutionVariables: 'global.variables.yml'
  subscriptionId: 'a8203460-7902-4329-8171-c459c80371d1'
  location: 'norwayeast'
  templateFilePath: './basic-web-app.bicep'
  parameterFilePath: './.parameters/basic-web-app.parameters.json'

jobs:
  ###################################
  #   Validate and Deploy Solution  #
  ###################################

  job_deploy_solution:
    name: 'Deploy Bicep Solution'
    runs-on: ubuntu-latest
      steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Validate and Deploy Bicep deployment'
        uses: actions/deploy-solution.action.yml
        with:
          subscriptionId: '${{ env.subscriptionId }}'
          location: '${{ env.location }}'
          templateFilePath: '${{ env.templateFilePath }}'
          parameterFilePath: '${{ env.parameterFilePath }}'
