name: '.Solution - Basic Web App Pipeline'

on:
  push:
    branches:
    - main
    paths:
    - '.github/actions/templates/**'
    - 'solutions/**'

env:
  #solutionVariables: 'global.variables.yml'
  subscriptionId: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
  location: 'norwayeast'
  templateFilePath: './solutions/basic-web-app.bicep'
  parameterFilePath: './solutions/.parameters/basic-web-app.parameters.json'
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  ###################################
  #   Validate and Deploy Solution  #
  ###################################

  job_deploy_solution:
    name: 'Deploy Bicep Solution'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Validate and Deploy Bicep deployment'
        uses: ./.github/actions/templates/deploySolution
        with:
          subscriptionId: '${{ env.subscriptionId }}'
          location: '${{ env.location }}'
          templateFilePath: '${{ env.templateFilePath }}'
          parameterFilePath: '${{ env.parameterFilePath }}'
